const clock = document.querySelector('#clock');
function updateClock(){clock.textContent=new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date())}
updateClock();setInterval(updateClock,60000);
const viewCount=document.querySelector('#view-count');
// Сохраняем бейдж в браузере: внешний сервис вызывается только раз в день.
if(viewCount){const counterUrl=viewCount.dataset.counterSrc;const now=new Date();const today=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;const dayKey=`kilibick-view-${today}`;const badgeKey='kilibick-view-badge';const cachedBadge=localStorage.getItem(badgeKey);if(cachedBadge)viewCount.src=cachedBadge;if(localStorage.getItem(dayKey)!=='1'){fetch(`${counterUrl}&t=${Date.now()}`).then(response=>response.blob()).then(blob=>new Promise(resolve=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.readAsDataURL(blob)})).then(dataUrl=>{viewCount.src=dataUrl;localStorage.setItem(badgeKey,dataUrl);localStorage.setItem(dayKey,'1')}).catch(()=>{viewCount.src=counterUrl;localStorage.setItem(dayKey,'1')})}}
// Убираем постоянные pointermove-обновления: они вызывали лишние перерисовки на слабых устройствах.
const audio=document.querySelector('#audio');const playButton=document.querySelector('#play-button');const musicTile=document.querySelector('#music');const state=document.querySelector('#music-state');const progress=document.querySelector('#progress-bar');
if(audio&&playButton){const toggleMusic=async()=>{try{if(audio.paused){await audio.play();musicTile.classList.add('is-playing');if(state)state.textContent='сейчас играет';playButton.querySelector('.play-icon').textContent='❚❚'}else{audio.pause();musicTile.classList.remove('is-playing');if(state)state.textContent='пауза';playButton.querySelector('.play-icon').textContent='▶'}}catch(error){if(state)state.textContent='не удалось загрузить music.mp3';}};playButton.addEventListener('click',toggleMusic);if(musicTile)musicTile.addEventListener('click',event=>{if(event.target!==playButton&&!playButton.contains(event.target))toggleMusic()});audio.addEventListener('timeupdate',()=>{const ratio=audio.duration?audio.currentTime/audio.duration:0;progress.style.width=`${ratio*100}%`;});audio.addEventListener('ended',()=>{musicTile.classList.remove('is-playing');if(state)state.textContent='нажми, чтобы слушать';playButton.querySelector('.play-icon').textContent='▶';progress.style.width='0%';});}

