const clock = document.querySelector('#clock');
function updateClock(){clock.textContent=new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date())}
updateClock();setInterval(updateClock,60000);
// Убираем постоянные pointermove-обновления: они вызывали лишние перерисовки на слабых устройствах.
const audio=document.querySelector('#audio');const playButton=document.querySelector('#play-button');const musicTile=document.querySelector('#music');const state=document.querySelector('#music-state');const progress=document.querySelector('#progress-bar');
if(audio&&playButton){const toggleMusic=async()=>{try{if(audio.paused){await audio.play();musicTile.classList.add('is-playing');if(state)state.textContent='сейчас играет';playButton.querySelector('.play-icon').textContent='❚❚'}else{audio.pause();musicTile.classList.remove('is-playing');if(state)state.textContent='пауза';playButton.querySelector('.play-icon').textContent='▶'}}catch(error){if(state)state.textContent='не удалось загрузить music.mp3';}};playButton.addEventListener('click',toggleMusic);if(musicTile)musicTile.addEventListener('click',event=>{if(event.target!==playButton&&!playButton.contains(event.target))toggleMusic()});audio.addEventListener('timeupdate',()=>{const ratio=audio.duration?audio.currentTime/audio.duration:0;progress.style.width=`${ratio*100}%`;});audio.addEventListener('ended',()=>{musicTile.classList.remove('is-playing');if(state)state.textContent='нажми, чтобы слушать';playButton.querySelector('.play-icon').textContent='▶';progress.style.width='0%';});}
const viewCount=document.querySelector('#view-count');const today=new Date().toLocaleDateString('en-CA');const viewKey='kilibick-view-'+today;
async function readViews(){try{const response=await fetch('https://api.counterapi.dev/v1/kilibick27-site/views');const data=await response.json();if(viewCount)viewCount.textContent=Number(data.count||0).toLocaleString('ru-RU')}catch(error){if(viewCount)viewCount.textContent='0'}}
async function registerView(){try{const response=await fetch('https://api.counterapi.dev/v1/kilibick27-site/views/up');const data=await response.json();if(viewCount)viewCount.textContent=Number(data.count||0).toLocaleString('ru-RU')}catch(error){readViews()}}
if(viewCount){if(localStorage.getItem(viewKey)!=='1'){registerView();localStorage.setItem(viewKey,'1')}else{readViews()}}
